Imported Upstream version 1.3.5~rc3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6224,7 +6224,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 
@@ -6245,7 +6245,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 
@@ -15459,7 +15459,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 ;;
 esac
-rm -f -r conftest*
+rm -f conftest*
   if test $ac_cv_sys_file_offset_bits = unknown; then
     { echo "$as_me:$LINENO: checking for _LARGE_FILES value needed for large files" >&5
 echo $ECHO_N "checking for _LARGE_FILES value needed for large files... $ECHO_C" >&6; }
@@ -15580,7 +15580,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 ;;
 esac
-rm -f -r conftest*
+rm -f conftest*
   fi
 fi
 
@@ -22715,7 +22715,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 
@@ -22736,7 +22736,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 
@@ -24909,7 +24909,7 @@ else
 echo "${ECHO_T}no" >&6; }
 
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 
 
@@ -26433,7 +26433,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_type_uid_t=no
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 { echo "$as_me:$LINENO: result: $ac_cv_type_uid_t" >&5
@@ -26790,7 +26790,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_type_getgroups=int
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 fi
@@ -26836,10 +26836,10 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   pr_cv_header_timer_t="no"
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 { echo "$as_me:$LINENO: result: $pr_cv_header_timer_t" >&5
@@ -31055,7 +31055,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   pr_cv_header_utmaxtype="no"
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 { echo "$as_me:$LINENO: result: $pr_cv_header_utmaxtype" >&5
@@ -31080,7 +31080,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   pr_cv_header_ut_host="no"
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 { echo "$as_me:$LINENO: result: $pr_cv_header_ut_host" >&5
@@ -31105,7 +31105,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   pr_cv_header_ut_exit="no"
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 { echo "$as_me:$LINENO: result: $pr_cv_header_ut_exit" >&5
@@ -31164,7 +31164,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   pr_cv_header_syslog_log_cron="no"
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 { echo "$as_me:$LINENO: result: $pr_cv_header_syslog_log_cron" >&5
@@ -31194,7 +31194,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   pr_cv_header_syslog_log_ftp="no"
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 { echo "$as_me:$LINENO: result: $pr_cv_header_syslog_log_ftp" >&5
@@ -31461,7 +31461,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_os_cray=no
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 { echo "$as_me:$LINENO: result: $ac_cv_os_cray" >&5
@@ -31740,7 +31740,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_prog_gcc_traditional=no
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 
   if test $ac_cv_prog_gcc_traditional = no; then
@@ -31757,7 +31757,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
   $EGREP "$ac_pattern" >/dev/null 2>&1; then
   ac_cv_prog_gcc_traditional=yes
 fi
-rm -f -r conftest*
+rm -f conftest*
 
   fi
 fi
@@ -36919,7 +36919,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   have_psstrings="no"
 fi
-rm -f -r conftest*
+rm -f conftest*
 
     if test "$have_psstrings" = "yes"; then
 	cat >>confdefs.h <<\_ACEOF
@@ -37014,7 +37014,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   pf_cv_argv_type="writeable"
 fi
-rm -f -r conftest*
+rm -f conftest*
 
 fi
 { echo "$as_me:$LINENO: result: $pf_cv_argv_type" >&5
@@ -37232,19 +37232,87 @@ done
 echo "${ECHO_T}no" >&6; }
 
 if test x"$pr_use_mysql" = xyes; then
-  # Check for other MySQL-specific functionality here
+    saved_cppflags="$CPPFLAGS"
   saved_ldflags="$LDFLAGS"
   saved_libs="$LIBS"
-  saved_cppflags="$CPPFLAGS"
 
-  # Fiddle with CPPFLAGS, LDFLAGS
-  CPPFLAGS="$CPPFLAGS $ac_build_addl_includes"
+    CPPFLAGS="$CPPFLAGS $ac_build_addl_includes"
   LDFLAGS="$LDFLAGS $ac_build_addl_libdirs"
 
     LIBS=`echo "$LIBS" | sed -e 's/-lsupp//g'`;
   LIBS="$LIBS -lm -lmysqlclient -lz"
 
-  # For Bug#3669, we need to check for make_scrambled_password_323.
+
+  { echo "$as_me:$LINENO: checking for MySQL's make_scrambled_password" >&5
+echo $ECHO_N "checking for MySQL's make_scrambled_password... $ECHO_C" >&6; }
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+      #ifdef HAVE_STDLIB_H
+      # include <stdlib.h>
+      #endif
+      #ifdef HAVE_SYS_TYPES_H
+      # include <sys/types.h>
+      #endif
+      #include <mysql.h>
+
+int
+main ()
+{
+
+      char output[32];
+      char *input = NULL;
+      (void) make_scrambled_password(output, input);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+      { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MYSQL_MAKE_SCRAMBLED_PASSWORD 1
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+      { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
   { echo "$as_me:$LINENO: checking for MySQL's make_scrambled_password_323" >&5
 echo $ECHO_N "checking for MySQL's make_scrambled_password_323... $ECHO_C" >&6; }
   cat >conftest.$ac_ext <<_ACEOF
@@ -37341,7 +37409,7 @@ main ()
       char output[32];
       char *input = NULL;
       size_t inputlen = 0;
-      my_make_scrambled_password(output, input, inputlen);
+      (void) my_make_scrambled_password(output, input, inputlen);
 
   ;
   return 0;
@@ -37388,8 +37456,78 @@ fi
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 
-  # restore CPPFLAGS, LDFLAGS
-  CPPFLAGS="$saved_cppflags"
+  { echo "$as_me:$LINENO: checking for MySQL's my_make_scrambled_password_323" >&5
+echo $ECHO_N "checking for MySQL's my_make_scrambled_password_323... $ECHO_C" >&6; }
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+      #ifdef HAVE_STDLIB_H
+      # include <stdlib.h>
+      #endif
+      #ifdef HAVE_SYS_TYPES_H
+      # include <sys/types.h>
+      #endif
+      #include <mysql.h>
+
+int
+main ()
+{
+
+      char output[32];
+      char *input = NULL;
+      size_t inputlen = 0;
+      (void) my_make_scrambled_password_323(output, input, inputlen);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+      { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MYSQL_MY_MAKE_SCRAMBLED_PASSWORD_323 1
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+      { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+    CPPFLAGS="$saved_cppflags"
   LDFLAGS="$saved_ldflags"
   LIBS="$saved_libs"
 fi
@@ -38161,13 +38299,13 @@ echo "${ECHO_T}no" >&6; }
    fi
    rm -f conftest*
 
-    { echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -Wunreachable-code" >&5
-echo $ECHO_N "checking whether ${CC-cc} accepts -Wunreachable-code... $ECHO_C" >&6; }
+    { echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -Wformat" >&5
+echo $ECHO_N "checking whether ${CC-cc} accepts -Wformat... $ECHO_C" >&6; }
    echo 'void f(){}' > conftest.c
-   if test -z "`${CC-cc} -c -Wunreachable-code conftest.c 2>&1`"; then
+   if test -z "`${CC-cc} -c -Wformat conftest.c 2>&1`"; then
      { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-     CFLAGS="$CFLAGS -Wunreachable-code"
+     CFLAGS="$CFLAGS -Wformat"
    else
      { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
@@ -38187,6 +38325,45 @@ echo "${ECHO_T}no" >&6; }
    fi
    rm -f conftest*
 
+    { echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -Wimplicit-function-declaration" >&5
+echo $ECHO_N "checking whether ${CC-cc} accepts -Wimplicit-function-declaration... $ECHO_C" >&6; }
+   echo 'void f(){}' > conftest.c
+   if test -z "`${CC-cc} -c -Wimplicit-function-declaration conftest.c 2>&1`"; then
+     { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+     CFLAGS="$CFLAGS -Wimplicit-function-declaration"
+   else
+     { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+   fi
+   rm -f conftest*
+
+    { echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -Wmaybe-uninitialized" >&5
+echo $ECHO_N "checking whether ${CC-cc} accepts -Wmaybe-uninitialized... $ECHO_C" >&6; }
+   echo 'void f(){}' > conftest.c
+   if test -z "`${CC-cc} -c -Wmaybe-uninitialized conftest.c 2>&1`"; then
+     { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+     CFLAGS="$CFLAGS -Wmaybe-uninitialized"
+   else
+     { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+   fi
+   rm -f conftest*
+
+    { echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -Wpointer-to-int-cast" >&5
+echo $ECHO_N "checking whether ${CC-cc} accepts -Wpointer-to-int-cast... $ECHO_C" >&6; }
+   echo 'void f(){}' > conftest.c
+   if test -z "`${CC-cc} -c -Wpointer-to-int-cast conftest.c 2>&1`"; then
+     { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+     CFLAGS="$CFLAGS -Wpointer-to-int-cast"
+   else
+     { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+   fi
+   rm -f conftest*
+
     { echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -Wstack-protector" >&5
 echo $ECHO_N "checking whether ${CC-cc} accepts -Wstack-protector... $ECHO_C" >&6; }
    echo 'void f(){}' > conftest.c
@@ -38194,6 +38371,19 @@ echo $ECHO_N "checking whether ${CC-cc} accepts -Wstack-protector... $ECHO_C" >&
      { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
      CFLAGS="$CFLAGS -Wstack-protector"
+   else
+     { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+   fi
+   rm -f conftest*
+
+    { echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -Wunreachable-code" >&5
+echo $ECHO_N "checking whether ${CC-cc} accepts -Wunreachable-code... $ECHO_C" >&6; }
+   echo 'void f(){}' > conftest.c
+   if test -z "`${CC-cc} -c -Wunreachable-code conftest.c 2>&1`"; then
+     { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+     CFLAGS="$CFLAGS -Wunreachable-code"
    else
      { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
@@ -39865,7 +40055,7 @@ do
     cat >>$CONFIG_STATUS <<_ACEOF
     # First, check the format of the line:
     cat >"\$tmp/defines.sed" <<\\CEOF
-/^[	 ]*#[	 ]*undef[	 ][	 ]*$ac_word_re[	 ]*/b def
+/^[	 ]*#[	 ]*undef[	 ][	 ]*$ac_word_re[	 ]*\$/b def
 /^[	 ]*#[	 ]*define[	 ][	 ]*$ac_word_re[(	 ]/b def
 b
 :def
