Policy bumped to 4.1.3

diff --git a/debian/proftpd-basic.preinst b/debian/proftpd-basic.preinst
--- a/debian/proftpd-basic.preinst
+++ b/debian/proftpd-basic.preinst
@@ -10,22 +10,17 @@ set -e
 #
 
 if [ "$1" = "upgrade" ]; then
-	 if [ -e /usr/sbin/invoke-rc.d ]; then
-         	invoke-rc.d proftpd stop >/dev/null 2>&1 || true 
-	 else
-	 	/etc/init.d/proftpd stop >/dev/null 2>&1 || true
-	 fi
-
-         # Scoreboard file format changed in 1.2.9
-         # Now stopping all inetd sessions and removing it to ensure
-         # a clean upgrade
-         if dpkg --compare-versions "$2" lt "1.2.9-1"; then
-                if [ `pgrep proftpd|wc -l` -ne 0 ]; then
-                        pkill proftpd
-                        sleep 2
-                fi
-                rm -f /run/proftpd/proftpd.scoreboard
-         fi
+     invoke-rc.d proftpd stop >/dev/null 2>&1 || true 
+     # Scoreboard file format changed in 1.2.9
+     # Now stopping all inetd sessions and removing it to ensure
+     # a clean upgrade
+     if dpkg --compare-versions "$2" lt "1.2.9-1"; then
+            if [ `pgrep proftpd|wc -l` -ne 0 ]; then
+                    pkill proftpd
+                    sleep 2
+            fi
+            rm -f /run/proftpd/proftpd.scoreboard
+     fi
 fi
 
 exit 0
